### ISSUE TITLE
Can't build the main branch

### ISSUE THREAD

**Issue by remyleone** [crossplane-contrib/provider-jet-aws#194]
### What happened?

```
$ make generate
15:59:19 [ .. ] generating provider schema for hashicorp/aws 3.56.0
15:59:22 [ OK ] generating provider schema for hashicorp/aws 3.56.0
15:59:22 [ .. ] verify dependencies have expected content
all modules verified
15:59:25 [ OK ] go modules dependencies verified
15:59:25 [ .. ] go generate darwin_amd64
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x1e94dd6]

goroutine 1 [running]:
github.com/crossplane/terrajet/pkg/types.init.0()
        /Users/sieben/workspace/upstream/provider-jet-aws/.work/pkg/pkg/mod/github.com/crossplane/terrajet@v0.4.0-rc.0.0.20220421012850-4f9db892a4ae/pkg/types/reference.go:73 +0x116
exit status 2
apis/generate.go:35: running "go": exit status 1
15:59:30 [FAIL]
make[1]: *** [go.generate] Error 1
make: *** [generate] Error 2

```

### How can we reproduce it?

`make generate` on the main branch.

### What environment did it happen in?
Crossplane version:

**Comment by waldner** [comment]
The build is failing for me too, but with a different error:

```
$ make generate
19:49:41 [ .. ] verify dependencies have expected content
go: github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0 (replaced by github.com/gdavison/terraform-plugin-sdk/v2@v2.0.2-0.20210714181518-b5a3dc95a675): version "v2.0.2-0.20210714181518-b5a3dc95a675" invalid: unknown revision b5a3dc95a675
20:08:12 [FAIL]
make[1]: *** [build/makelib/golang.mk:218: go.vendor.lite] Error 1
make: *** [build/makelib/common.mk:418: generate] Error 2
```

**Comment by haarchri** [comment]
Think you need to use go1.17
